from utils.gemini import ask_gemini


class RecoveryAgent:

    def run(self, context):

        prompt = f"""
You are an expert SQL debugging assistant.

A SQL query generated by an AI failed during execution.

Your task is to correct the SQL while preserving the user's original intent.

User Question:
{context.user_query}

Original SQL:
{context.validated_sql}

Execution Error:
{context.execution_error}

Database Schema:
{context.full_schema}

Instructions:
- Carefully analyze the execution error.
- Use ONLY tables and columns present in the schema.
- Do NOT invent table names or column names.
- Preserve the user's original intent.
- Return ONLY the corrected SQL.
- Do NOT include explanations.
- Do NOT wrap the SQL inside markdown.

Corrected SQL:
"""

        corrected_sql = ask_gemini(prompt)

        # Remove markdown if Gemini returns it
        corrected_sql = (
            corrected_sql
            .replace("```sql", "")
            .replace("```", "")
            .strip()
        )

        # Update the SQL to be executed again
        context.validated_sql = corrected_sql

        context.logs.append({
            "agent": "Recovery Agent",
            "status": "Completed",
            "message": "Corrected SQL based on execution error."
        })

        return context